name: Deploy Static Content
on:
  push:
    branches: ["main"] # Ensure this matches your branch name (main or master)
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Changed this to '.' because your files are in the root of the repo
          path: '.' 
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
